
# Community

Forwards partners with community groups within and beyond the R community to work towards more inclusive tech and open source/research software communities.

The R community groups with a particular mission to support members of underrepresented groups include:

- [R-Ladies](https://rladies.org/): the mission of R-Ladies is to achieve proportionate representation by encouraging, inspiring, and empowering people of genders currently underrepresented in the R community. 
- [AfricaR](https://r4africa.org/): working to achieve improved representation by encouraging, inspiring, and empowering the African population of all genders who are underrepresented in the global R community.
- [MiR](https://mircommunity.com/): MiR Community hopes to provide a space of belonging and support for people who identify as underrepresented minority R useRs. They aim to provide opportunities for underrepresented minority useRs to contribute to the R community.
- [Blind R User Group](https://www.nfbnet.org/mailman/listinfo/blindrug_nfbnet.org): a mailing list for anyone interested in knowing more about (or improving) the use of R by blind people. This would include blind students, their support staff, or anyone having an interest in how blind people will make use of R and related tools.
- [Rainbow R (R LGBTQ+)](https://rainbowr.netlify.app/): a community that supports, promotes and connects LGBTQ+ people who code in the R language.

In addition, there are many general R User Groups open to all, some of which are listed in the following places:

 - [R Community Explorer](https://benubah.github.io/r-community-explorer/rugs.html) a dashboard that tracks meetups listed on Meetup.com.
 - [R User Group List](https://jumpingrivers.github.io/meetingsR/r-user-groups.html) maintained on GitHub by the R consultancy Jumping Rivers.
Others may be found by searching on Meetup or Facebook.

Forwards is a taskforce set up by the R Foundation, the not-for-profit organization that supports the R project. Other organizations we work with include:

- [R Consortium](https://www.r-consortium.org/about) a not-for-profit consortium of business set up to support the worldwide community of users, maintainers and developers of R software.
    - The R Consortium has a [Diversity & Inclusion Working Group](https://github.com/RConsortium/RCDI-WG/tree/master).
- [Why R? Foundation](http://whyr.pl/foundation/about/) a non-governmental organization set up by a team of R enthusiasts coming from both business and academia who aim to support local R communities around the world. 