---
title: "Contribution"
---

The Forwards on-ramps team work on initiatives to support useRs to become developeRs, with a focus on contributing to the R project via packages on CRAN/Bioconductor or via contribution to R Core. Find out more about specific projects below.

* **First Contributions using GitHub/RStudio**: Many R packages are version controlled using git and hosted on a platform such as GitHub or GitLab. This enables people from the general R community to submit contributions to packages to fix issues, e.g. to correct a typo in the documentation, to fix a bug or even to propose an improvement or new feature. The [first-contributions](https://github.com/forwards/first-contributions) repository is designed to give first-timers a place to practice the workflow of forking a GitHub repository, making a small change and submitting a pull request back to the original repository for the maintainers to review.

* **R Contribution Working Group**: This group is a collaboration between R Core, R community groups (including Forwards, the R Consortium Diversity and Inclusion Working Group, R-Ladies, MiR) and members of the wider R community. Its aim is to encourage new contributors to R core, with a focus on diversity and inclusion. See the [R Contribution Working Group](https://forwards.github.io/rcontribution) subsite for more information, including how to join the Slack group for anyone interested in R core contribution.

See also the [Education](/edu) page, which includes learning resources for useRs wanting to learn about package development.
