---
title: "About"
---

## Background

The task force was set up by the [R Foundation](https://www.r-project.org/foundation/) in December 2015 to address the underrepresentation of women and rebranded in Janurary 2017 to accommadate more under-represented groups such as LGBT, minority ethnic groups in the R community.

The members of the task force were invited to participate based on their interest in routing for specific under-represented groups and their contributions in the area, to reflect different genders, ethnic groups, work contexts, career stages and aspects of the R project (e.g. CRAN and Bioconductor). Currently, the task force is expanding and welcomes anybody with such interest to join our sub-teams as below. 

* **Community**: General outreach to help people from under-represented groups get into R and develop as useRs.

* **Conferences**: Focusing on R Foundation conferences,liaising with organizers/program committee on policies.

* **On-ramps to becoming a developR**: Guidance on how to contribute to core R/Bioconductor, marketing package development to women.

* **Social Media**: Posting to Twitter and/or Facebook, soliciting blog posts and publishing them, maintaining website. 

* **Surveys**: Running and analysing surveys polled at useR!, maintaining Data page on website and packaging up data and tools.

* **Teaching**: Methodology and materials designed for under-represented groups, workshops targeted at under-represented groups.

If interested, please contact rowforwards@gmail.com. 

The task force is happy to engage with other individuals and organisations (such as [R-ladies](http://r-ladies.org)) that are concerned about this issue and actively seek outside contributions on specific tasks. 


## Core Team Members

[Heather Turner](https://uk.linkedin.com/in/heathrturnr)-**Chair**. She works as a freelance statistical programmer and is on the board of the R Foundation. [More about Heather](http://heatherturner.net/)

Gina Griffin- **'Community' team leader**. She is a Social Worker and a trauma therapist and now works with data related to research and program evaluation in R. [More about Gina](https://github.com/Allyris)

[Kevin O'Brien](https://ie.linkedin.com/in/kobriendublin)- **'Community' team leader**. He is a freelance statistical consultant and university teacher as well as the main organizer of Dublin R User Group wtih strong links with other data science user groups in Ireland and beyond.[More about Kevin](https://www.codinggrace.com/)

Julie Josse-**'Conference' team leader**. She is a professor of statistics at Ecole Polytechnique in France and promotes her passion of R through R classes and statistical teaching. [More about Julie](http://juliejosse.com/)

[Jenny Bryan](https://twitter.com/JennyBryan)- **Team leader for 'On-ramps to becoming a developR"**. She used to be an Assoc.Professor of Statistics at the University of British Columbia and now a developer at [RStudio](https://www.rstudio.com), a member of the R Foundation and serves in the leadership of rOpenSci. [More about Jenny ](https://www.stat.ubc.ca/~jenny/)

[Michael Lawrence](https://www.linkedin.com/in/michael-lawrence-74a9b482/)- **Team leader for 'On-ramps to becoming a developR**. He's a Computational Biologist at Genentech and a member on R Foundation, R core and Bioconductor Core. 


[Tracy Shen](https://www.linkedin.com/in/jiatracyshen/)- **'Social Media' team leader**. She is a Data Analyst at AccuWeather, Inc and holds the Data Science Specialization Certificate in R by Johns Hopkins University. [More about Tracy](https://github.com/tbs08)

[David Smith](https://www.linkedin.com/in/dmsmith/)- **'Social Media' team leader**. He is the R Community Lead at Microsoft, and editor of the Revolutions blog. 

[Jasmine Dumas](https://www.linkedin.com/in/jasminedumas/)- **'Surveys' team leader**. She is a Data Scientist at Simple and author of  `shinyGEO`, `ttbbeer`, `shinyLP`, `gramr` packages. [More about Jasmine](https://jasdumas.github.io/).

[Madlene Hamilton](https://www.linkedin.com/in/madlenehamilton/)- **'Surveys' team leader**. She is a research scientist and has been working on data projects in the social science and innovation arena for over 20 years. [More about Madlene](https://twitter.com/madlenehamilton)

[Carolin Strobl](http://www.psychologie.uzh.ch/en/fachrichtungen/methoden/team/carolinstrobl.html)-**'Survey' team leader**. She is a Professor in the Department of Psychology at the University of Zurich, established the [Zurich R Courses](http://www.zhrcourses.uzh.ch/en.html) and co-founded the [Psychoco](https://eeecon.uibk.ac.at/psychoco/courses.html) workshops on psychometric computing. 

[Di Cook](http://dicook.github.io/)- **'Teaching' team leader**. She is a Professor in the Department of Econometrics & Business Statistics at Monash University, a regular mentor on [R Google Summer of Code projects](https://github.com/rstats-gsoc) and was elected to the R Foundation in 2016.

[Emily Dodwell](https://www.linkedin.com/in/emilymdodwell/)- **'Teaching' team administrator**. She is a Data Scientist and R enthusiast in the Big Data Research Statistics Department at AT&T Labs, as well as an active member of the New York City R community. 

[Isabella Gollini](https://www.linkedin.com/in/isabellagollini/)- **'Teaching' team leader**. She is a Lecturer in Statistics at Birkbeck, University of London and a RLadies mentor. [More about Isabella](https://sites.google.com/site/isabellagollini/)

Jonathan Godfrey- **Multiple member at 'Conferences', 'Surveys', 'Teaching' teams**. He was the first totally blind person in the world to gain employment as a Lecturer in Statistics (Massey University, NZ) and now assists Forwards through advice on how disabled people can be included in the R community.[More about Jonanthan](https://R-Resources.massey.ac.nz/BrailleR)




## Sub Team Members

[Noa Tamir](https://www.linkedin.com/in/noatamir)- **'Community' team member**. [More about Noa](noatamir.com)

Gina Merchant- **'Conferences', 'Social Media' team member**. [More about Gina](http://gmerchant.ucsd.edu)

[Charlotte Wickham](https://www.linkedin.com/in/charlotte-wickham-793a011a)- **'On-ramps' team member**.[More about Charlotte](http://cwick.co.nz)
 
 
[Joyce Robbins](https://www.linkedin.com/in/joycerobbins/)- **'Teaching' team member**.[More about Joyce](http://www.joyce-robbins.com/about/)

[Joslynn Lee](https://www.linkedin.com/in/joslynnlee/)- **'Community' team member**.

[Ileena Mitra](https://www.linkedin.com/in/ileena-mitra-86a5955a/)- **'Community' team member**. [More about Ileena](https://ileenamitra.github.io/)

[Rudolf Debelak](https://www.linkedin.com/in/rudolf-debelak-5214a85b/)- **'Surveys' team member**. [More about Rugolf](https://www.psychologie.uzh.ch/en/fachrichtungen/methoden/team/rudolfdebelak.html)

John Fox- **'Surveys' team member**. [More about John](http://socserv.mcmaster.ca/jfox/)

Wenfeng Qin- **'Social Media' team member**. [More about Wenfeng](https://github.com/qinwf)

Maëlle Salmon- **'Surveys' team member**.[More about Maëlle](http://www.masalmon.eu/)

Stella Bollman- **'Surveys' team member**.

Andrea Foulkes- **'Teaching' team member**.

Hadley Wickham- **'Teaching' team member**. 
