<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Julie Josse and Heather Turner">
<meta name="dcterms.date" content="2017-06-17">

<title>Forwards - useR! 2016 participants and R programming: a multivariate analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="https://forwards.github.io/images/forwards.svg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Forwards</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../community.html" rel="" target="">
 <span class="menu-text">Community</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../conferences.html" rel="" target="">
 <span class="menu-text">Conferences</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../edu/index.html" rel="" target="">
 <span class="menu-text">Education</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contribution.html" rel="" target="">
 <span class="menu-text">Contribution</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-other" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Other</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-other">    
        <li>
    <a class="dropdown-item" href="../../docs/index.html" rel="" target="">
 <span class="dropdown-text">Reports</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../privacy-policy.html" rel="" target="">
 <span class="dropdown-text">Forwards Privacy Policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../logo-information.html" rel="" target="">
 <span class="dropdown-text">Forwards logo information</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://hachyderm.io/@R_Forwards" rel="me" target=""><i class="bi bi-mastodon" role="img" aria-label="mastodon">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../blog/index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:rowforwards@mail.com" rel="" target=""><i class="bi bi-envelope" role="img" aria-label="email">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools tools-wide">
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/forwards/website_source">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/forwards/website_source">
            Report a Bug
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a></li>
  <li><a href="#coding" id="toc-coding" class="nav-link" data-scroll-target="#coding">Coding</a></li>
  </ul></li>
  <li><a href="#analysis-of-the-uses-of-r" id="toc-analysis-of-the-uses-of-r" class="nav-link" data-scroll-target="#analysis-of-the-uses-of-r">Analysis of the uses of R</a></li>
  <li><a href="#analysis-of-the-perception-of-the-r-programming-language" id="toc-analysis-of-the-perception-of-the-r-programming-language" class="nav-link" data-scroll-target="#analysis-of-the-perception-of-the-r-programming-language">Analysis of the perception of the R programming language</a></li>
  <li><a href="#perception-and-uses-of-r" id="toc-perception-and-uses-of-r" class="nav-link" data-scroll-target="#perception-and-uses-of-r">Perception and uses of R</a></li>
  <li><a href="#relationship-with-demographic" id="toc-relationship-with-demographic" class="nav-link" data-scroll-target="#relationship-with-demographic">Relationship with demographic</a></li>
  <li><a href="#similarities-between-respondents" id="toc-similarities-between-respondents" class="nav-link" data-scroll-target="#similarities-between-respondents">Similarities between respondents</a>
  <ul class="collapse">
  <li><a href="#cluster-1" id="toc-cluster-1" class="nav-link" data-scroll-target="#cluster-1">Cluster 1</a></li>
  <li><a href="#cluster-2" id="toc-cluster-2" class="nav-link" data-scroll-target="#cluster-2">Cluster 2</a></li>
  <li><a href="#cluster-3" id="toc-cluster-3" class="nav-link" data-scroll-target="#cluster-3">Cluster 3</a></li>
  <li><a href="#cluster-4" id="toc-cluster-4" class="nav-link" data-scroll-target="#cluster-4">Cluster 4</a></li>
  <li><a href="#to-sum-up" id="toc-to-sum-up" class="nav-link" data-scroll-target="#to-sum-up">To sum-up</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">useR! 2016 participants and R programming: a multivariate analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Julie Josse and Heather Turner </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 17, 2017</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background</h3>
<p>The useR! survey gathers responses to questions on different themes for 455 attendees: demographic characteristics, R programming and involvement in the R community. The separate analyses of each question in each theme are detailed in the posts <a href="blog/2017/01/13/mapping-users/">Mapping useRs</a>, <a href="blog/2017/03/11/users-relationship-with-r/">useRs Relationship with R</a> and <a href="blog/2017/06/19/users-participation-in-the-r-community/">Community Involvement of useRs</a>. Here, we aim at understanding attendees’ joint responses to the questions of the survey for a given theme. In other words, we would like to highlight the relationships between their answers, as well as to highlight the similarities between the respondents. Multiple correspondence analysis (MCA) is a dimensionality reduction method which allows to explore and visualize a set of categorical variables. It can be seen as the counterpart of PCA for categorical data. The aim of this document is to go beyond univariate analyses and to present the results of a multivariate analyses of the R programming questions using MCA. A corresponding analysis of the R community questions is detailed in <a href="docs/mca_community_user2016_survey/">a companion report</a>.</p>
</section>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">Questions</h3>
<p>We base our study on the following questions:</p>
<section id="demography" class="level4">
<h4 class="anchored" data-anchor-id="demography">Demography</h4>
<ul>
<li>Q1 What did you register as at useR! 2016?</li>
<li>Q2 What is your gender?</li>
<li>Q3 In what year were you born?</li>
<li>Q4 To what racial or ethnic group(s) do you identify?</li>
<li>Q5 In what country do you currently reside?</li>
<li>Q6 Do you identify as LGBT (Lesbian, Gay, Bisexual, Asexual and/or Transgender)?</li>
<li>Q7 What is the highest level of education you have completed?</li>
<li>Q8 What is your current (primary) employment status?</li>
<li>Q9 Is your current job full-time or part-time?</li>
<li>Q10 Are you a caregiver for children or adult dependents on a regular basis?</li>
</ul>
</section>
<section id="r-programming" class="level4">
<h4 class="anchored" data-anchor-id="r-programming">R programming</h4>
<ul>
<li>Q11 How long have you been using R for?</li>
<li>Q12 Did you have previous programming experience before beginning to use R?</li>
<li>Q13 Which of the following do you do? Tick any that apply among
<ul>
<li>Q13A I use functions from existing R packages to analyze data</li>
<li>Q13B I write R code designed to make my work easier, such as loops or conditionals or functions</li>
<li>Q13C I write R functions for use by myself or my collaborators</li>
<li>Q13D I contribute to R packages (on CRAN or elsewhere)</li>
<li>Q13E I have written my own R package</li>
<li>Q13F I have written my own R package and released it on CRAN or Bioconductor (or shared it on GitHub, R-Forge or similar platforms)</li>
</ul></li>
<li>Q14 Do you use R as a recreational activity, primarily as part of a job or both?</li>
<li>Q15 How much do you agree or disagree with the following statements?
<ul>
<li>Q15A Writing R is fun</li>
<li>Q15B Writing R is considered cool or interesting by my peers?</li>
<li>Q15C Writing R is a monotonous task</li>
<li>Q15D Writing R is difficult</li>
</ul></li>
<li>Q16 Would you recommend R to friends or colleagues as a programming language to learn?</li>
<li>Q17 What would be your number one argument for/against learning R?</li>
</ul>
<p>Questions Q1-Q10 focus on the demographic characteristics of the respondents while questions Q11, Q13 and Q14 are related to the use of R, and questions Q15 to Q17 to the perception of R. Note that Q12 is about programming in general and not specifically dedicated to R.</p>
<p>We first focus on the topic “uses of R” and we will consider the perception questions in a second step. The demographic questions are also used in the analysis in order to help in the interpretation and to describe the profile of R programming answers.</p>
</section>
</section>
<section id="coding" class="level3">
<h3 class="anchored" data-anchor-id="coding">Coding</h3>
<p>Questions Q1, Q5 and Q17 have a category of answer <em>Other (please specify)</em>. The “free” answers have been gathered in different categories and included as new categories in the questions. The new variables (with more levels) are named Q1_new, Q5_new and Q17_new. In addition, some categories name have been modified to make them easily understandable.</p>
<p>Note that questions Q13_A to Q13_F are answered by ticking one box indicating that the respondent agrees with the category. Consequently, if a box is unchecked, it is impossible to know if they disagree or if they don’t answer the question. Such responses are recoded as <em>yes</em> if the box is checked and recoded as <em>no</em> otherwise.</p>
</section>
</section>
<section id="analysis-of-the-uses-of-r" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-the-uses-of-r">Analysis of the uses of R</h2>
<p>The following graphic summarizes relationships between the answers to the “uses of R” questions. To interpret the main dimensions of variability in the response profiles, we base our analysis on the proximities between categories. Two categories are close on the graph when individuals who have selected the first category also tend to take the other category.</p>
<p><img src="unnamed-chunk-3-1.png" title="plot of chunk unnamed-chunk-3" alt="plot of chunk unnamed-chunk-3" style="display: block; margin: auto;"></p>
<p>Proximities between categories Q11.NA and Q14.NA indicate that people who did not answer Q11 (How long have you been using R for?) often did not answer Q14 (Do you use R as a recreational activity, primarily as part of a job or both?). However, it only concerns 16 individuals.</p>
<p>We can see on the graph a gradient which shows the relationship between the question Q11 related to the experience in R programming and the question Q13 related to the use of R, with people on the right, who have recently started using R, and people on the left, who have used R for a long time. In particular, the users with more than 10 years’ experience have already written their own package or contributed to packages, while people with less than 2 years’ experience haven’t. The gradient can be clearly interpreted and shows the progression in gaining new skills.</p>
<p>The beginners in R seem to be trying R during their free time. This is less true for experienced users who have probably gained their experience during their job. Note that beginners in R are very few among respondents (9 people with less than 6 months’ experience).</p>
<p>The graph of the individuals allows identification of the individuals located at the top right who do not answer some questions. These individuals did not answer any of the questions related to their use of R but answered the demographic questions. Interestingly, one of them indicated they just discovered R (in the text answer Q25). This explanation could also be valid for the other ones, explaining why they agree to participate to the study, yet only answer a few questions. This comment is in line with the previous graph, in which categories <em>NA</em> are on the right, which is the location of inexperienced users.</p>
</section>
<section id="analysis-of-the-perception-of-the-r-programming-language" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-the-perception-of-the-r-programming-language">Analysis of the perception of the R programming language</h2>
<p><img src="unnamed-chunk-5-1.png" title="plot of chunk unnamed-chunk-5" alt="plot of chunk unnamed-chunk-5" style="display: block; margin: auto;"></p>
<p>The analysis of questions related to the perception of the R language (Q15, Q16, Q17) shows again that attendees who did not answer one question often did not answer others (1st dimension). More interestingly, the second dimension of the graph highlights that people thinking very strongly that R is monotonous also think that it is not fun, not cool, or even think R is poor. It highlights that among respondents there is a sub-population of people who do not appreciate R. However, it concerns around 10 individuals.</p>
<p>Interestingly, these respondents tend to recommend R to a friend as a programming language to learn, so that they recognize some interest.</p>
</section>
<section id="perception-and-uses-of-r" class="level2">
<h2 class="anchored" data-anchor-id="perception-and-uses-of-r">Perception and uses of R</h2>
<p>Does the perception of the R language differ according to the experience of the user? To answer this question, the perception variables are projected as supplementary variables on the graph obtained with the “uses of R” variables. Supplementary variables are not used to build the dimensions of variability, they are projected <em>a posteriori</em> and help for the interpretation.</p>
<p><img src="unnamed-chunk-7-1.png" title="plot of chunk unnamed-chunk-7" alt="plot of chunk unnamed-chunk-7" style="display: block; margin: auto;"></p>
<p>We note that experienced users particularly appreciate R. They find that R is fun, not monotonous and they recommend to use it.</p>
</section>
<section id="relationship-with-demographic" class="level2">
<h2 class="anchored" data-anchor-id="relationship-with-demographic">Relationship with demographic</h2>
<p><img src="unnamed-chunk-8-1.png" title="plot of chunk unnamed-chunk-8" alt="plot of chunk unnamed-chunk-8" style="display: block; margin: auto;"></p>
<p>Demographic variables are also projected as supplementary variables. We excluded the ethnic group variable (Q4) and the country of residence variable (Q5) because of the large number of infrequent categories. The graph above shows that the demographic characteristics are significantly related to the user profiles. An analysis of variance with demographic variables as covariates, and the coordinates of the individuals on the dimensions as explanatory variables, has been performed<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. The graph shows that people with a doctorate are more highly represented among advanced users. This also shows that men are more highly represented than women among the most advanced users. As stated in the post <a href="https:://forwards.github.io/blog/2017/03/11/users-relationship-with-r/">useRs Relationship with R</a>, it could be explained by the fact that women tend to be younger, but here we note that the variable Age does not significantly explain the coordinates of the individuals on the graph. To get more insight into this possible confounding effect, we created a variable sex-age and represent it. The plot confirms that men are over-represented amongst the advanced users.</p>
<p><img src="unnamed-chunk-9-1.png" title="plot of chunk unnamed-chunk-9" alt="plot of chunk unnamed-chunk-9" style="display: block; margin: auto;"><img src="unnamed-chunk-9-2.png" title="plot of chunk unnamed-chunk-9" alt="plot of chunk unnamed-chunk-9" style="display: block; margin: auto;"></p>
</section>
<section id="similarities-between-respondents" class="level2">
<h2 class="anchored" data-anchor-id="similarities-between-respondents">Similarities between respondents</h2>
<p>The participants are clustered according to their answers to the uses of R questions only (Q11, Q13, Q14). To do this, a hierarchical clustering is performed on K principal components of the MCA. The rationale is to improve the stability of the clustering by building it from denoised data.</p>
<p>Several rules can be used to select the number of components used for the clustering. Here we choose 12 dimensions which corresponds to 95% of the projected inertia (variance) of the data.</p>
<p><img src="unnamed-chunk-12-1.png" title="plot of chunk unnamed-chunk-12" alt="plot of chunk unnamed-chunk-12" style="display: block; margin: auto;"></p>
<p>The number of clusters is chosen according to the barplot of the inertia gains<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> which suggests 3 clusters.</p>
<p>However, since a cluster with non-respondents is expected, we consider 4 clusters to have a more interpretable clustering.</p>
<p><img src="unnamed-chunk-13-1.png" title="plot of chunk unnamed-chunk-13" alt="plot of chunk unnamed-chunk-13" style="display: block; margin: auto;"></p>
<p>The first cluster located on the left represent the experienced users while the second cluster gathers the intermediate users and the third one the beginners. The fourth cluster is constituted with people who did not answer.</p>
<p>The size of each cluster is as follows:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: right;">171</td>
<td style="text-align: right;">260</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13</td>
</tr>
</tbody>
</table>
<p><em>i.e.</em> in terms of proportions:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">proportion</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.03</td>
</tr>
</tbody>
</table>
<p>We now interpret the clusters.</p>
<section id="cluster-1" class="level3">
<h3 class="anchored" data-anchor-id="cluster-1">Cluster 1</h3>
<p>To help us describing the first cluster, we use statistical tests to compare the proportion of each category in the cluster versus the proportion in the population of the respondents. Of course, for variables that have been used to build the clusters (Q11, Q13, Q14), this test is only indicative, but for others (demographic questions or perception questions), the p.values can be interpreted.</p>
<table class="table">
<colgroup>
<col style="width: 64%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Cla/Mod</th>
<th style="text-align: right;">Mod/Cla</th>
<th style="text-align: right;">Global</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q13_F=rel_pkg_yes</td>
<td style="text-align: right;">96.77</td>
<td style="text-align: right;">87.72</td>
<td style="text-align: right;">34.07</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13_D=ctb_pkg_yes</td>
<td style="text-align: right;">88.37</td>
<td style="text-align: right;">88.89</td>
<td style="text-align: right;">37.80</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q13_E=wrt_pkg_yes</td>
<td style="text-align: right;">71.85</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">52.31</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13_C=wrt_func_yes</td>
<td style="text-align: right;">42.93</td>
<td style="text-align: right;">97.66</td>
<td style="text-align: right;">85.49</td>
<td style="text-align: right;">3.5e-10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q13_B=wrt_code_yes</td>
<td style="text-align: right;">42.35</td>
<td style="text-align: right;">97.08</td>
<td style="text-align: right;">86.15</td>
<td style="text-align: right;">1.4e-08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q2=Men</td>
<td style="text-align: right;">46.64</td>
<td style="text-align: right;">77.19</td>
<td style="text-align: right;">62.20</td>
<td style="text-align: right;">2.2e-07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q7=Doctorate</td>
<td style="text-align: right;">50.75</td>
<td style="text-align: right;">59.06</td>
<td style="text-align: right;">43.74</td>
<td style="text-align: right;">3.5e-07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q11=&gt; 10 years</td>
<td style="text-align: right;">57.14</td>
<td style="text-align: right;">39.77</td>
<td style="text-align: right;">26.15</td>
<td style="text-align: right;">4.6e-07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q15=fun_Strongly agree</td>
<td style="text-align: right;">49.54</td>
<td style="text-align: right;">62.57</td>
<td style="text-align: right;">47.47</td>
<td style="text-align: right;">5.7e-07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q14=For both recreational and job/educational purposes.</td>
<td style="text-align: right;">52.50</td>
<td style="text-align: right;">49.12</td>
<td style="text-align: right;">35.16</td>
<td style="text-align: right;">1.7e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q1_new=Q1_new_Academic/Govt</td>
<td style="text-align: right;">46.81</td>
<td style="text-align: right;">51.46</td>
<td style="text-align: right;">41.32</td>
<td style="text-align: right;">0.00071</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q8=Q8_Employed non-permanently in academia</td>
<td style="text-align: right;">57.63</td>
<td style="text-align: right;">19.88</td>
<td style="text-align: right;">12.97</td>
<td style="text-align: right;">0.00089</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q8=Q8_Employed permanently in academia</td>
<td style="text-align: right;">53.95</td>
<td style="text-align: right;">23.98</td>
<td style="text-align: right;">16.70</td>
<td style="text-align: right;">0.00157</td>
</tr>
</tbody>
</table>
<p>The table can be interpreted as follows:</p>
<ul>
<li>first row indicates that 96.77% of individuals that have released their own R package are in cluster 1; 87.72% of individuals in this cluster have released their own R package, and 34.07% of individuals in the population have released their own R package.<br>
</li>
<li>row 7 indicates that 50.75% of individuals with a doctorate are in this cluster; 59.06% of individuals in this cluster have a doctorate, and 43.74% of individuals in the population have a doctorate. We can reject at risk 3.47e-07 the null hypothesis <em>the proportion of respondents with a doctorate in the first cluster is the same than the proportion in the population of the respondents</em>. This first table only represents the results when the proportion in the cluster is larger than the proportion in the population.</li>
</ul>
<p>To wrap-up, the tests results confirm that <strong>cluster 1 gathers experienced users</strong>. In this cluster, there is an over-representation of people with a doctorate, men, or people employed in academia. It is also a cluster where the proportion of people strongly seeing R programming as fun is large. In the same line, people in cluster 1 are more likely to use R for both recreational and job/educational purposes.</p>
<p>This second table represents the categories that are underrepresented in cluster 1.</p>
<table class="table">
<colgroup>
<col style="width: 63%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Cla/Mod</th>
<th style="text-align: right;">Mod/Cla</th>
<th style="text-align: right;">Global</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q13_F=rel_pkg_no</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">12.28</td>
<td style="text-align: right;">65.93</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13_D=ctb_pkg_no</td>
<td style="text-align: right;">6.71</td>
<td style="text-align: right;">11.11</td>
<td style="text-align: right;">62.20</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q13_E=wrt_pkg_no</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">47.69</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13_C=wrt_func_no</td>
<td style="text-align: right;">6.06</td>
<td style="text-align: right;">2.34</td>
<td style="text-align: right;">14.51</td>
<td style="text-align: right;">3.5e-10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q13_B=wrt_code_no</td>
<td style="text-align: right;">7.94</td>
<td style="text-align: right;">2.92</td>
<td style="text-align: right;">13.85</td>
<td style="text-align: right;">1.4e-08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q11=6-12 months</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">6.37</td>
<td style="text-align: right;">6.6e-07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q2=Women</td>
<td style="text-align: right;">23.08</td>
<td style="text-align: right;">22.81</td>
<td style="text-align: right;">37.14</td>
<td style="text-align: right;">6.6e-07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q1_new=Q1_new_Industry</td>
<td style="text-align: right;">26.46</td>
<td style="text-align: right;">29.24</td>
<td style="text-align: right;">41.54</td>
<td style="text-align: right;">3.3e-05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q8=Q8_Employed in industry</td>
<td style="text-align: right;">26.23</td>
<td style="text-align: right;">28.07</td>
<td style="text-align: right;">40.22</td>
<td style="text-align: right;">3.7e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q14=Q14.NA</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">3.52</td>
<td style="text-align: right;">0.00045</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q11=1-2 years</td>
<td style="text-align: right;">11.43</td>
<td style="text-align: right;">2.34</td>
<td style="text-align: right;">7.69</td>
<td style="text-align: right;">0.00046</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q7=Masters degree</td>
<td style="text-align: right;">28.34</td>
<td style="text-align: right;">30.99</td>
<td style="text-align: right;">41.10</td>
<td style="text-align: right;">0.00065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q14=Primarily as part of a job or educational course;</td>
<td style="text-align: right;">31.64</td>
<td style="text-align: right;">50.88</td>
<td style="text-align: right;">60.44</td>
<td style="text-align: right;">0.00131</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q11=Q11.NA</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">2.86</td>
<td style="text-align: right;">0.00196</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q5=United States</td>
<td style="text-align: right;">32.91</td>
<td style="text-align: right;">60.82</td>
<td style="text-align: right;">69.45</td>
<td style="text-align: right;">0.00217</td>
</tr>
</tbody>
</table>
<p>US people are under-represented in cluster 1. We can imagine that only people deeply using R are motivated to go to the US for such a conference due to the costs.</p>
</section>
<section id="cluster-2" class="level3">
<h3 class="anchored" data-anchor-id="cluster-2">Cluster 2</h3>
<p>Cluster 2 can be described as a cluster of <strong>intermediate users</strong> who use R since 1-2 years or less, but more than 6 months. They use R functions, but don’t write their own functions or packages. They appreciate R, but use it primarily for their job. They are more employed in the industry. This cluster gathers more women, more undergraduate and master and people from the US.</p>
<table class="table">
<colgroup>
<col style="width: 63%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Cla/Mod</th>
<th style="text-align: right;">Mod/Cla</th>
<th style="text-align: right;">Global</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q13_F=rel_pkg_no</td>
<td style="text-align: right;">85.33</td>
<td style="text-align: right;">98.46</td>
<td style="text-align: right;">65.93</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13_D=ctb_pkg_no</td>
<td style="text-align: right;">85.51</td>
<td style="text-align: right;">93.08</td>
<td style="text-align: right;">62.20</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q13_E=wrt_pkg_no</td>
<td style="text-align: right;">89.86</td>
<td style="text-align: right;">75.00</td>
<td style="text-align: right;">47.69</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q11=6-12 months</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">11.15</td>
<td style="text-align: right;">6.37</td>
<td style="text-align: right;">4.4e-08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q14=Primarily as part of a job or educational course;</td>
<td style="text-align: right;">66.91</td>
<td style="text-align: right;">70.77</td>
<td style="text-align: right;">60.44</td>
<td style="text-align: right;">2.2e-07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q2=Women</td>
<td style="text-align: right;">71.60</td>
<td style="text-align: right;">46.54</td>
<td style="text-align: right;">37.14</td>
<td style="text-align: right;">1.4e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q11=1-2 years</td>
<td style="text-align: right;">88.57</td>
<td style="text-align: right;">11.92</td>
<td style="text-align: right;">7.69</td>
<td style="text-align: right;">4.0e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q8=Q8_Employed in industry</td>
<td style="text-align: right;">67.76</td>
<td style="text-align: right;">47.69</td>
<td style="text-align: right;">40.22</td>
<td style="text-align: right;">0.00017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q1_new=Q1_new_Industry</td>
<td style="text-align: right;">67.20</td>
<td style="text-align: right;">48.85</td>
<td style="text-align: right;">41.54</td>
<td style="text-align: right;">0.00026</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q15=fun_Agree</td>
<td style="text-align: right;">67.20</td>
<td style="text-align: right;">48.08</td>
<td style="text-align: right;">40.88</td>
<td style="text-align: right;">0.00031</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q7=Masters degree</td>
<td style="text-align: right;">66.31</td>
<td style="text-align: right;">47.69</td>
<td style="text-align: right;">41.10</td>
<td style="text-align: right;">0.00096</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q2Q3=20-28_Women</td>
<td style="text-align: right;">79.07</td>
<td style="text-align: right;">13.08</td>
<td style="text-align: right;">9.45</td>
<td style="text-align: right;">0.00185</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q16=rcmd_Yes</td>
<td style="text-align: right;">59.09</td>
<td style="text-align: right;">95.00</td>
<td style="text-align: right;">91.87</td>
<td style="text-align: right;">0.00558</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q2Q3=29-33_Women</td>
<td style="text-align: right;">75.56</td>
<td style="text-align: right;">13.08</td>
<td style="text-align: right;">9.89</td>
<td style="text-align: right;">0.00786</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q5=United States</td>
<td style="text-align: right;">61.08</td>
<td style="text-align: right;">74.23</td>
<td style="text-align: right;">69.45</td>
<td style="text-align: right;">0.01118</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13=use_func_yes</td>
<td style="text-align: right;">58.63</td>
<td style="text-align: right;">95.38</td>
<td style="text-align: right;">92.97</td>
<td style="text-align: right;">0.02258</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q7=Undergraduate degree</td>
<td style="text-align: right;">71.15</td>
<td style="text-align: right;">14.23</td>
<td style="text-align: right;">11.43</td>
<td style="text-align: right;">0.02953</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q15_D=difficult_Disagree</td>
<td style="text-align: right;">62.56</td>
<td style="text-align: right;">50.77</td>
<td style="text-align: right;">46.37</td>
<td style="text-align: right;">0.03045</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q2Q3=&gt;58_Men</td>
<td style="text-align: right;">80.00</td>
<td style="text-align: right;">6.15</td>
<td style="text-align: right;">4.40</td>
<td style="text-align: right;">0.03401</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q10=Caryng_resp_No</td>
<td style="text-align: right;">60.18</td>
<td style="text-align: right;">76.15</td>
<td style="text-align: right;">72.31</td>
<td style="text-align: right;">0.03569</td>
</tr>
</tbody>
</table>
</section>
<section id="cluster-3" class="level3">
<h3 class="anchored" data-anchor-id="cluster-3">Cluster 3</h3>
<p>Cluster 3 gathers respondents with less than 6 months of experience in R. They do not have an opinion about the “fun” or “monotonous” nature of R. They use R in their free time and find that the main advantage of R is that it is an open source software. This cluster gather <strong>curious users</strong> discovering R in their free time. No demographic characteristics show-up in this group.</p>
<table class="table">
<colgroup>
<col style="width: 66%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Cla/Mod</th>
<th style="text-align: right;">Mod/Cla</th>
<th style="text-align: right;">Global</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q11=&lt; 6 months</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">81.82</td>
<td style="text-align: right;">1.98</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q14=Primarily as a recreational activity, in your free time;</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">36.36</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">1.9e-07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q13_C=wrt_func_no</td>
<td style="text-align: right;">12.12</td>
<td style="text-align: right;">72.73</td>
<td style="text-align: right;">14.51</td>
<td style="text-align: right;">1.6e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13_B=wrt_code_no</td>
<td style="text-align: right;">11.11</td>
<td style="text-align: right;">63.64</td>
<td style="text-align: right;">13.85</td>
<td style="text-align: right;">0.00016</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q15=fun_No opinion</td>
<td style="text-align: right;">13.33</td>
<td style="text-align: right;">36.36</td>
<td style="text-align: right;">6.59</td>
<td style="text-align: right;">0.00400</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q16=rcmd_No</td>
<td style="text-align: right;">14.29</td>
<td style="text-align: right;">27.27</td>
<td style="text-align: right;">4.62</td>
<td style="text-align: right;">0.01195</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q15_C=monotonous_No opinion</td>
<td style="text-align: right;">7.46</td>
<td style="text-align: right;">45.45</td>
<td style="text-align: right;">14.73</td>
<td style="text-align: right;">0.01564</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q4=Native American</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">9.09</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.02418</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q17_new=Open source</td>
<td style="text-align: right;">11.11</td>
<td style="text-align: right;">27.27</td>
<td style="text-align: right;">5.93</td>
<td style="text-align: right;">0.02484</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13_E=wrt_pkg_no</td>
<td style="text-align: right;">4.15</td>
<td style="text-align: right;">81.82</td>
<td style="text-align: right;">47.69</td>
<td style="text-align: right;">0.02518</td>
</tr>
</tbody>
</table>
</section>
<section id="cluster-4" class="level3">
<h3 class="anchored" data-anchor-id="cluster-4">Cluster 4</h3>
<p>As expected, cluster 4 not described in detail here is a cluster where individuals do not answer questions, or do not check boxes.</p>
</section>
<section id="to-sum-up" class="level3">
<h3 class="anchored" data-anchor-id="to-sum-up">To sum-up</h3>
<p>The respondents can be classified in 3 clusters according to their uses of R:</p>
<ul>
<li>The experienced users (38%): they have an in depth knowledge of R programming, even creating their own package. They are mainly men, academic, with a doctorate</li>
<li>The intermediate users (57%): they mainly use functions from existing packages, but do not write their own functions. They are mainly women, people from industry, who are undergraduate or have a master degree. In addition, they are more likely from US.</li>
<li>The curious users (3%): they have discovered R very recently. They don’t have an opinion that is already formed. They appreciate the open source nature of R.</li>
</ul>
<p>A fourth cluster of people that didn’t answer the question could be considered. It represents 2% of individuals. They could be potential future users that didn’t have any experience in R at the moment to complete the questionnaire.</p>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>Missing values often occur on all the R programming questions. One possible explanation backed-up by the free text answer of one individual and by the proximity to the inexperienced users, is that the values are missing because the participants do not program in R. If so, the deletion of missing individuals for subsequent analyses would reduce the scope of the analysis since the sample would be restricted to R users only. However, the cluster of individuals who do not answer these questions, do not answer any of the R community questions as well. Consequently, it can also be individuals who have started answering the questions and stopped before finishing. So we decide to delete this group for the other analyses.</p>
<!-- More precisely, we face to a missing not at random mechanism since we cannot explain missing values from collected variables. It would have been interesting to include a question to know if the participant has previously done R programming or not, making easier handling missing values. -->
<p>Practices of R are linked to the experience of the users. In particular, users with more than 10 years’ experience have already written their own package, while people with less than 2 years’ experience haven’t.</p>
<p>A focus on the demographic characteristics of the participants highlights experienced users are more likely men than women, more likely from academia than from industry and more likely people with a doctorate than without. They often use R both for their job and for pleasure. Intermediate users use R for less than 2 years, they mainly use existing packages. Intermediate users are mainly women, people with undergraduate and master degrees and less men or people with doctoral degrees. Beginners are trying R during their free time.</p>
<p>To conclude, we should suggest using “yes” and “no” answers for the checkboxes to distinguish missing values from “no”. In addition, we should be cautious about over-interpretation and keep in mind that their is a strong age effect: there are many women who are young.</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>For more details about the use of analysis of variance to interpret the MCA graphs, see: Francois Husson, Jerome Pages, Sebastien Le. Exploratory Multivariate Analysis by Example Using R. CRC Press Taylor &amp; Francis, pp.240, 2010, Chapman &amp; Hall/CRC Computer Science &amp; Data Analysis.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>For more details about the classification based on principal components methods, see the reference above.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© 2023 Forwards, under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a> license.<br></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>