---
type: index
---

## Mission

Leading the R community forwards in widening the participation of women and other under-represented groups.

Find out more [about](about) the task force.

<div style = "display: flex; align-items: flexstart;">
<div style = "width:50%">
<!-- need to use <a></a> here as markdown href don't seem to work in div -->
## News

*2017/01/13* Open call to join the taskforce, [further details](/blog/2017/01/13/call-to-join-forwards/).

*2016/11/13* Heather Turner's presentation from <a href="http://erum.ue.poznan.pl/">eRum 2016</a>, "Addressing the Gender Gap in the R Project", now on <a href=https://www.youtube.com/watch?v=fp6JY7cirww&list=PLCsJUtCRSFbejqCqAURNVOFFpoDCMeuO5>YouTube</a> [<a href="http://rpubs.com/hturner/eRum2016">slides</a>].

*2016/11/04* Jenny Bryan, Di Cook and Julie Josse are elected as ordinary members of the R Foundation, bringing the total number of women to 5 out of 37.

*2016/10/20* Di Cook presents the work of the task force at <a href="https://ww2.amstat.org/meetings/wsds/2016/onlineprogram/AbstractDetails.cfm?AbstractID=303353)">Women in Statistics and Data Science 2016</a>.

*2016/08/22* R Consortium approves funding for a <a href="https://www.r-consortium.org/blog/2016/08/22/the-r-consortium-funds-three-projects-in-july">joint proposal</a> from the San Francisco and London R-ladies groups for alignment and global expansion.

*2016/06/27* Proportion of women at useR! 2016 rises to 28% from 19% at useR! 2015.

*2016/06/23* Heather Turner presents the work of the task force at <a href="https://r2016-toulouse.sciencesconf.org/">Rencontres R 2016</a> [<a href="http://rpubs.com/hturner/RencontresR2016">slides</a>].
</div>
<!--https://dev.twitter.com/web/embedded-timelines/parameters -->
<!-- data-tweet-limit="3" -->
<div style = "width:50%">
## Latest Tweets
<a class="twitter-timeline" data-height = "500" data-theme="light" data-chrome="noheader" href="https://twitter.com/R_Forwards"></a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
</div>

## Events

R-ladies meet-ups and other relevant events. 
      
<br>     
<iframe src="https://calendar.google.com/calendar/embed?title=FORWARDS%20calendar&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=98i553ll9id8l35qmj5u05ui7o%40group.calendar.google.com&amp;&amp;src=3ahe2f1q4a3upfu8096g5odu0n5h8icp%40import.calendar.google.com&amp;color=%232952A3&amp;ctz=Australia%2FSydney" style="border-width: 0; display: block; margin: 0 auto;" width="600" height="400" frameborder="0" scrolling="no"></iframe>

 