<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Julie Josse and Heather Turner">
<meta name="dcterms.date" content="2017-06-18">

<title>Forwards - useR! 2016 participants and the R community: a multivariate analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="https://forwards.github.io/images/forwards.svg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Forwards</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../community.html" rel="" target="">
 <span class="menu-text">Community</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../conferences.html" rel="" target="">
 <span class="menu-text">Conferences</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../edu/index.html" rel="" target="">
 <span class="menu-text">Education</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../contribution.html" rel="" target="">
 <span class="menu-text">Contribution</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../data.html" rel="" target="">
 <span class="menu-text">Data</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-other" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Other</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-other">    
        <li>
    <a class="dropdown-item" href="../../docs/index.html" rel="" target="">
 <span class="dropdown-text">Reports</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../privacy-policy.html" rel="" target="">
 <span class="dropdown-text">Forwards Privacy Policy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../logo-information.html" rel="" target="">
 <span class="dropdown-text">Forwards logo information</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://hachyderm.io/@R_Forwards" rel="me" target=""><i class="bi bi-mastodon" role="img" aria-label="mastodon">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../blog/index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:rowforwards@mail.com" rel="" target=""><i class="bi bi-envelope" role="img" aria-label="email">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools tools-wide">
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/forwards/website_source">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/forwards/website_source">
            Report a Bug
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a></li>
  <li><a href="#r-community-questions" id="toc-r-community-questions" class="nav-link" data-scroll-target="#r-community-questions">R community questions</a></li>
  <li><a href="#coding" id="toc-coding" class="nav-link" data-scroll-target="#coding">Coding</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">Analysis</a>
  <ul class="collapse">
  <li><a href="#first-dimension-of-variability" id="toc-first-dimension-of-variability" class="nav-link" data-scroll-target="#first-dimension-of-variability">First dimension of variability</a></li>
  <li><a href="#second-dimension-of-variability" id="toc-second-dimension-of-variability" class="nav-link" data-scroll-target="#second-dimension-of-variability">Second dimension of variability</a></li>
  <li><a href="#relationship-with-demographic" id="toc-relationship-with-demographic" class="nav-link" data-scroll-target="#relationship-with-demographic">Relationship with demographic</a></li>
  <li><a href="#similarities-between-respondents" id="toc-similarities-between-respondents" class="nav-link" data-scroll-target="#similarities-between-respondents">Similarities between respondents</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">useR! 2016 participants and the R community: a multivariate analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Julie Josse and Heather Turner </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 18, 2017</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background</h3>
<p>The useR! survey gathers responses to questions on different themes for 455 attendees: demographic characteristics, R programming and involvement in the R community. The separate analyses of each question in each theme are detailed in the posts <a href="blog/2017/01/13/mapping-users/">Mapping useRs</a>, <a href="blog/2017/03/11/users-relationship-with-r/">useRs Relationship with R</a> and <a href="blog/2017/06/19/users-participation-in-the-r-community/">Community Involvement of useRs</a>. A multivariate analysis of the R programming questions is detailed in <a href="docs/mca_programming_user2016_survey/">a companion report</a>. Here, we perform MCA on the R community questions.</p>
</section>
<section id="r-community-questions" class="level3">
<h3 class="anchored" data-anchor-id="r-community-questions">R community questions</h3>
<p>Questions are the following ones:</p>
<ul>
<li>Q18 Do you consider yourself part of the R community?</li>
<li>Q19 Which of the following resources do you use for support? Select all that apply
<ul>
<li>Q19_A The R mailing lists</li>
<li>Q19_B The #rstats hashtag on Twitter</li>
<li>Q19_C The R StackOverflow queues</li>
<li>Q19_D The R IRC channel</li>
<li>Q19_E The rOpenSci mailing lists or chat forums</li>
<li>Q19_F The Bioconductor support site</li>
<li>Q19_H Other</li>
</ul></li>
<li>Q20 What would be your preferred medium for R community news (e.g.&nbsp;events, webinars, opportunities)?</li>
<li>Q21 Do you attend R user group meetings in your local area?</li>
<li>Q22 If you do: you do: what type of user group is it?</li>
<li>Q23 If you do not: why not?</li>
<li>Q24 Which of the following would make you more likely to participate in the R community, or improve your experience? Tick any that apply.
<ul>
<li>Q24_A New R user group near me (specify location in comments box)</li>
<li>Q24_B New R user group near me aimed at my demographic (specify relevant group in comments box)</li>
<li>Q24_C Free local introductory R workshops</li>
<li>Q24_D Paid local advanced R workshops</li>
<li>Q24_E R workshop at conference in my domain (specify domain/conference in comments box)</li>
<li>Q24_F R workshop aimed at my demographic (specify relevant group in comments box)</li>
<li>Q24_G Mentoring (e.g.&nbsp;first CRAN submission/useR! abstract submission/GitHub contribution)</li>
<li>Q24_H Training in non-English language (specify language in comments box)</li>
<li>Q24_I Training that accommodates my disability (specify disability in comments box)</li>
<li>Q24_J Online forum to discuss R-related issues</li>
<li>Q24_K Online support group for my demographic (specify relevant group in comments box)</li>
<li>Q24_L Special facilities at R conferences (give further detail in comments box)</li>
<li>Q24_M Comments on answers above</li>
</ul></li>
<li>Q25 What other ideas do you have for improving the R community?</li>
<li>Q26 Do you have any feedback for the survey authors?</li>
</ul>
</section>
<section id="coding" class="level3">
<h3 class="anchored" data-anchor-id="coding">Coding</h3>
<ul>
<li><p>Question Q20 has a category “others” which corresponds to free text answers. We add new categories for this variable by grouping common answers and we name the new variables with the suffix “_new’’. For instance, there is a variable Q20_new with a new category medium_R-bloggers.</p></li>
<li><p>Question Q19_H also corresponds to free text answers. It has been recoded with Q19_H_new to Q19_N_new by grouping common answers: for instance, Q19_K_new has two categories Github_yes or Github_no.</p></li>
<li><p>Q21, Q22 and Q23 have been merged in a variable Q21_new since Q22 and Q23 are filled-in depending on the answer on Q21. For example, for Q21 <em>Do you attend R user group meetings in your local area?</em>, if the respondent answers <em>no</em>, they answer Q23 <em>If you do not: why not?</em>, with <em>I am too busy</em>. This is coded in the variable Q21_new, with the category <em>meeting_no_I am too busy</em>.</p></li>
<li><p>Q24_M, Q25 and Q26 are not analysed.</p></li>
<li><p>Non-respondents identified in the <em>MCA Rprogramming</em> document are also excluded since they do not answer to R community questions as well.</p></li>
<li><p>Categories are renamed to be easily understandable. In particular, the two categories for answers completed by checking a box are recoded as <em>yes</em>, if the box is checked, or recoded as <em>no</em> otherwise.</p></li>
</ul>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">Analysis</h2>
<p>MCA summarizes the relationships between the categories of the R community variables.</p>
<p><img src="unnamed-chunk-3-1.png" title="plot of chunk unnamed-chunk-3" alt="plot of chunk unnamed-chunk-3" style="display: block; margin: auto;"></p>
<p>To interpret the main dimensions of variability in the response profiles, we study the proximities between categories. Indeed, two categories are close on the graph if most respondents taking the first category also take the other category.</p>
<section id="first-dimension-of-variability" class="level3">
<h3 class="anchored" data-anchor-id="first-dimension-of-variability">First dimension of variability</h3>
<p>The first dimension (horizontal axis) opposes people that <strong>didn’t answer questions about involvement in the R community</strong> on the left, to the others on the right. More precisely, they did not answer Q21, Q18 and Q20 and did not check any boxes for the other questions (_no). Individuals with the smallest coordinates on the first dimension work more in the industry; this is confirmed by a statistical test, but this remains difficult to interpret.</p>
</section>
<section id="second-dimension-of-variability" class="level3">
<h3 class="anchored" data-anchor-id="second-dimension-of-variability">Second dimension of variability</h3>
<p>On the top, there are respondents who do not attend an R user group because they feel too inexperienced. They think that they would be more likely to participate in the R community or to improve their experience, if a user group, a workshop, or an online support dedicated to their socio-demographic group would be available. Facebook would be their preferred medium for R community news. They do not use Twitter (question Q19_B), (the category R_twitter_no corresponds to the answer <em>The #rstats hashtag on Twitter</em> for the question <em>Which of the following resources do you use for support?</em>). In addition, they do not like to use it as a medium for R community news (question Q20). They consider themselves as outside the R community.</p>
<p>On the bottom, in contrast, there are individuals who tend to consider themselves as part of the R community. They attend general R user group meetings and they use Twitter. Twitter would be their preferred medium for R community news.</p>
<p><img src="unnamed-chunk-4-1.png" title="plot of chunk unnamed-chunk-4" alt="plot of chunk unnamed-chunk-4" style="display: block; margin: auto;"></p>
</section>
<section id="relationship-with-demographic" class="level3">
<h3 class="anchored" data-anchor-id="relationship-with-demographic">Relationship with demographic</h3>
<p>In the following graph, answers about the demographic questions are projected as supplementary variables on the two first dimensions of variability. Supplementary variables are not used to build the dimensions of variability, but they are projected <em>a posteriori</em> to highlight relationships between the dimensions of variability and demographics. Thus, supplementary variables can be used to characterize the response profiles described previously.</p>
<p>Only demographic characteristics that are significantly related the R community profiles are represented. An analysis of variance with demographic variables as covariates, and the coordinates of the individuals on the dimensions as explanatory variables, has been performed.</p>
<p><img src="unnamed-chunk-5-1.png" title="plot of chunk unnamed-chunk-5" alt="plot of chunk unnamed-chunk-5" style="display: block; margin: auto;"></p>
<p>It appears that people having an undergraduate degree or a master degree are located at the top of the graph, while those with a doctorate are at the bottom. This would imply that people with undergraduate degree or master degree are more likely to consider themselves as outside the R community than people having a doctorate. The same comment holds for women versus men. It is interesting to note, caregivers for children or adult dependents tend to be at the bottom of the graph, while non-caregivers are on the top.</p>
<p>We represent the age categories on the map since some confounding effects with other demographic variables could explain the previous results. Youngest people tend to be on the top of the second axis, which suggests that they consider themselves as outside the community.</p>
<p><img src="unnamed-chunk-6-1.png" title="plot of chunk unnamed-chunk-6" alt="plot of chunk unnamed-chunk-6" style="display: block; margin: auto;"></p>
<p>To get more insights into this possible confounder effect, we created a new variable sex-age and represent it:</p>
<p><img src="unnamed-chunk-7-1.png" title="plot of chunk unnamed-chunk-7" alt="plot of chunk unnamed-chunk-7" style="display: block; margin: auto;"></p>
<p>It highlights that both young (men and women) and women do not consider themselves as part of the R community.</p>
</section>
<section id="similarities-between-respondents" class="level3">
<h3 class="anchored" data-anchor-id="similarities-between-respondents">Similarities between respondents</h3>
<p>A clustering of the participants is performed from their answers to questions about their involvement in the R community. More precisely a hierarchical clustering is performed on the principal components of MCA. The rationale is to improve the stability of the clustering by building it from denoised data rather than from the original dataset<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Several rules can be used to select the number of components used for the clustering. Here we choose 44 dimensions which corresponds to 95% of the projected inertia (variance) of the data.</p>
<p>The number of clusters is chosen according to the barplot of the inertia gains which suggests a partition with 3 clusters. However, this clustering is not relevant since most of respondents are in the same group:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">size</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
<p>We investigate the number of respondents in each group according to the number of components used to build the clustering:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">clust1</th>
<th style="text-align: right;">clust2</th>
<th style="text-align: right;">clust3</th>
<th style="text-align: right;">clust4</th>
<th style="text-align: right;">clust5</th>
<th style="text-align: right;">clust6</th>
<th style="text-align: right;">clust7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ncp=2</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">307</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=3</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">208</td>
<td style="text-align: right;">162</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=4</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">231</td>
<td style="text-align: right;">139</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=5</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">148</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=6</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">249</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=7</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">269</td>
<td style="text-align: right;">159</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=8</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">255</td>
<td style="text-align: right;">173</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=9</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">192</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=10</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">271</td>
<td style="text-align: right;">157</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=11</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">273</td>
<td style="text-align: right;">155</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=12</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">428</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=13</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=14</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=15</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=16</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=17</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=18</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=19</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=20</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ncp=21</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ncp=22</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">425</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>We choose to keep 10 components as this will keep enough information, while highlighting a new cluster in the previous big one.</p>
<p><img src="unnamed-chunk-12-1.png" title="plot of chunk unnamed-chunk-12" alt="plot of chunk unnamed-chunk-12" style="display: block; margin: auto;"></p>
<p>Respondents are grouped in the clusters as follows:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">%</td>
<td style="text-align: right;">2.71</td>
<td style="text-align: right;">61.17</td>
<td style="text-align: right;">35.44</td>
<td style="text-align: right;">0.68</td>
</tr>
</tbody>
</table>
<p><img src="unnamed-chunk-14-1.png" title="plot of chunk unnamed-chunk-14" alt="plot of chunk unnamed-chunk-14" style="display: block; margin: auto;"></p>
<p>From the previous interpretation of the two first dimensions of variability, the location of clusters on the graph allows providing a brief summary of the clusters: cluster 1 is the group of non-respondents, while cluster 2 contains some respondents who feel they are part of the R community unlike the cluster 3 respondents.</p>
<section id="cluster-1" class="level4">
<h4 class="anchored" data-anchor-id="cluster-1">Cluster 1</h4>
<p>To describe the first cluster more precisely, we use statistical tests to compare the proportion of each category in the cluster against the proportion in the population of the respondents.</p>
<p>Unsurprisingly, there is an over-representation of people that didn’t answer the questions about the involvement in the R community. Using the demographic characteristics, we can see that they are mainly from the industry.</p>
</section>
<section id="cluster-2" class="level4">
<h4 class="anchored" data-anchor-id="cluster-2">Cluster 2</h4>
<p>The following categories are over-represented in cluster 2:</p>
<table class="table">
<colgroup>
<col style="width: 68%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Cla/Mod</th>
<th style="text-align: right;">Mod/Cla</th>
<th style="text-align: right;">Global</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q24=new_gp_near_no</td>
<td style="text-align: right;">78.19</td>
<td style="text-align: right;">92.62</td>
<td style="text-align: right;">72.46</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q18=in_Rcommunity_yes</td>
<td style="text-align: right;">70.64</td>
<td style="text-align: right;">94.10</td>
<td style="text-align: right;">81.49</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q21=Yes</td>
<td style="text-align: right;">85.89</td>
<td style="text-align: right;">51.66</td>
<td style="text-align: right;">36.79</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q21_new=meeting_yes_A general user group</td>
<td style="text-align: right;">86.82</td>
<td style="text-align: right;">41.33</td>
<td style="text-align: right;">29.12</td>
<td style="text-align: right;">1.1e-13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q19_B=R_twitter_yes</td>
<td style="text-align: right;">85.59</td>
<td style="text-align: right;">37.27</td>
<td style="text-align: right;">26.64</td>
<td style="text-align: right;">3.4e-11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q24_C=free_workshop_no</td>
<td style="text-align: right;">66.75</td>
<td style="text-align: right;">94.10</td>
<td style="text-align: right;">86.23</td>
<td style="text-align: right;">3.1e-09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q20_new=medium_Twitter</td>
<td style="text-align: right;">90.00</td>
<td style="text-align: right;">23.25</td>
<td style="text-align: right;">15.80</td>
<td style="text-align: right;">8.3e-09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q19=R_mailing_yes</td>
<td style="text-align: right;">73.89</td>
<td style="text-align: right;">49.08</td>
<td style="text-align: right;">40.63</td>
<td style="text-align: right;">4.8e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q24_B=new_gp_demo_no</td>
<td style="text-align: right;">64.08</td>
<td style="text-align: right;">97.42</td>
<td style="text-align: right;">93.00</td>
<td style="text-align: right;">7.9e-06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q21_new=meeting_no_It is not necessary (I have the support I need)</td>
<td style="text-align: right;">96.15</td>
<td style="text-align: right;">9.23</td>
<td style="text-align: right;">5.87</td>
<td style="text-align: right;">3.5e-05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q24_D=paid_workshop_no</td>
<td style="text-align: right;">64.92</td>
<td style="text-align: right;">91.51</td>
<td style="text-align: right;">86.23</td>
<td style="text-align: right;">7.5e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q19_C=R_StackOverflow_yes</td>
<td style="text-align: right;">66.17</td>
<td style="text-align: right;">81.55</td>
<td style="text-align: right;">75.40</td>
<td style="text-align: right;">0.00020</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q21_new=meeting_no_I am too busy</td>
<td style="text-align: right;">77.92</td>
<td style="text-align: right;">22.14</td>
<td style="text-align: right;">17.38</td>
<td style="text-align: right;">0.00071</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q7=Doctorate</td>
<td style="text-align: right;">68.91</td>
<td style="text-align: right;">49.08</td>
<td style="text-align: right;">43.57</td>
<td style="text-align: right;">0.00334</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q1_new=Q1_new_Academic/Govt</td>
<td style="text-align: right;">69.02</td>
<td style="text-align: right;">46.86</td>
<td style="text-align: right;">41.53</td>
<td style="text-align: right;">0.00428</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q24_F=demo_workshop_no</td>
<td style="text-align: right;">62.65</td>
<td style="text-align: right;">97.79</td>
<td style="text-align: right;">95.49</td>
<td style="text-align: right;">0.00481</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q9=Part-time</td>
<td style="text-align: right;">93.33</td>
<td style="text-align: right;">5.17</td>
<td style="text-align: right;">3.39</td>
<td style="text-align: right;">0.00648</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q7=Professional degree or certification</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">3.69</td>
<td style="text-align: right;">2.26</td>
<td style="text-align: right;">0.00687</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q19_L_new=web_no</td>
<td style="text-align: right;">62.50</td>
<td style="text-align: right;">97.79</td>
<td style="text-align: right;">95.71</td>
<td style="text-align: right;">0.00928</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q24_K=online_demo_no</td>
<td style="text-align: right;">62.35</td>
<td style="text-align: right;">97.79</td>
<td style="text-align: right;">95.94</td>
<td style="text-align: right;">0.01753</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q19_F=Biocond_yes</td>
<td style="text-align: right;">80.65</td>
<td style="text-align: right;">9.23</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">0.01900</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q2Q3=&gt;58_Men</td>
<td style="text-align: right;">85.00</td>
<td style="text-align: right;">6.27</td>
<td style="text-align: right;">4.51</td>
<td style="text-align: right;">0.02259</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q3_cat=&gt;58</td>
<td style="text-align: right;">81.48</td>
<td style="text-align: right;">8.12</td>
<td style="text-align: right;">6.09</td>
<td style="text-align: right;">0.02320</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q2=Men</td>
<td style="text-align: right;">65.22</td>
<td style="text-align: right;">66.42</td>
<td style="text-align: right;">62.30</td>
<td style="text-align: right;">0.02582</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q2Q3=29-33_Men</td>
<td style="text-align: right;">74.14</td>
<td style="text-align: right;">15.87</td>
<td style="text-align: right;">13.09</td>
<td style="text-align: right;">0.02851</td>
</tr>
</tbody>
</table>
<p>The numbers read as follows, e.g.&nbsp;for Q18: 70.64% of individuals who consider themselves as part of the R community are in cluster 2; in cluster 2 94.1% of the individuals consider themselves as part of the R community, and 81.49% in the population of all the respondents consider themselves as part of the R community. The test is significant which implies that this cluster can be considered as a cluster with an over-representation of people considering themselves as part of the community. We conclude they are not interested in free workshops, online demos, etc. According to the demographic characteristics, there is an over-representation of people employed permanently in academia, people with caring responsibilities, as well as a significantly larger proportion of men and people with a doctorate.</p>
<p>We studied the categories under-represented in the cluster. However, since most of variables are binary, we do not get new information from this table. We note however that young people are under-represented, as well as people who didn’t participate in R user group meetings because of inexperience.</p>
</section>
<section id="cluster-3" class="level4">
<h4 class="anchored" data-anchor-id="cluster-3">Cluster 3</h4>
<table class="table">
<colgroup>
<col style="width: 68%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Cla/Mod</th>
<th style="text-align: right;">Mod/Cla</th>
<th style="text-align: right;">Global</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q24=new_gp_near_yes</td>
<td style="text-align: right;">81.97</td>
<td style="text-align: right;">63.69</td>
<td style="text-align: right;">27.54</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q21_new=meeting_no_There is no group nearby/the group is inactive</td>
<td style="text-align: right;">78.82</td>
<td style="text-align: right;">42.68</td>
<td style="text-align: right;">19.19</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q21=No</td>
<td style="text-align: right;">50.75</td>
<td style="text-align: right;">86.62</td>
<td style="text-align: right;">60.50</td>
<td style="text-align: right;">&lt; 2e-16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q18=in_Rcommunity_no</td>
<td style="text-align: right;">76.81</td>
<td style="text-align: right;">33.76</td>
<td style="text-align: right;">15.58</td>
<td style="text-align: right;">2.4e-14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q24_C=free_workshop_yes</td>
<td style="text-align: right;">73.77</td>
<td style="text-align: right;">28.66</td>
<td style="text-align: right;">13.77</td>
<td style="text-align: right;">5.9e-11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q21_new=meeting_no_I feel too inexperienced</td>
<td style="text-align: right;">90.32</td>
<td style="text-align: right;">17.83</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">7.2e-11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q19_B=R_twitter_no</td>
<td style="text-align: right;">43.69</td>
<td style="text-align: right;">90.45</td>
<td style="text-align: right;">73.36</td>
<td style="text-align: right;">2.5e-10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q24_D=paid_workshop_yes</td>
<td style="text-align: right;">62.30</td>
<td style="text-align: right;">24.20</td>
<td style="text-align: right;">13.77</td>
<td style="text-align: right;">4.8e-06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q24_B=new_gp_demo_yes</td>
<td style="text-align: right;">74.19</td>
<td style="text-align: right;">14.65</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">6.9e-06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q20_new=medium_Website</td>
<td style="text-align: right;">52.73</td>
<td style="text-align: right;">36.94</td>
<td style="text-align: right;">24.83</td>
<td style="text-align: right;">1.8e-05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q19=R_mailing_no</td>
<td style="text-align: right;">42.97</td>
<td style="text-align: right;">71.97</td>
<td style="text-align: right;">59.37</td>
<td style="text-align: right;">5.6e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q19_L_new=web_yes</td>
<td style="text-align: right;">68.42</td>
<td style="text-align: right;">8.28</td>
<td style="text-align: right;">4.29</td>
<td style="text-align: right;">0.00351</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q20_new=medium_Facebook</td>
<td style="text-align: right;">66.67</td>
<td style="text-align: right;">8.92</td>
<td style="text-align: right;">4.74</td>
<td style="text-align: right;">0.00351</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q8=Q8_Employed in industry</td>
<td style="text-align: right;">42.37</td>
<td style="text-align: right;">47.77</td>
<td style="text-align: right;">39.95</td>
<td style="text-align: right;">0.01354</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q3_cat=20-28</td>
<td style="text-align: right;">45.83</td>
<td style="text-align: right;">28.03</td>
<td style="text-align: right;">21.67</td>
<td style="text-align: right;">0.01803</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q24_F=demo_workshop_yes</td>
<td style="text-align: right;">60.00</td>
<td style="text-align: right;">7.64</td>
<td style="text-align: right;">4.51</td>
<td style="text-align: right;">0.02503</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q7=Undergraduate degree</td>
<td style="text-align: right;">50.00</td>
<td style="text-align: right;">15.92</td>
<td style="text-align: right;">11.29</td>
<td style="text-align: right;">0.02609</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q24_K=online_demo_yes</td>
<td style="text-align: right;">61.11</td>
<td style="text-align: right;">7.01</td>
<td style="text-align: right;">4.06</td>
<td style="text-align: right;">0.02707</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q2Q3=20-28_Women</td>
<td style="text-align: right;">50.00</td>
<td style="text-align: right;">15.29</td>
<td style="text-align: right;">10.84</td>
<td style="text-align: right;">0.02974</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q20_new=medium_Google+</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">1.91</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.04396</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q7=High school/Secondary school or lower</td>
<td style="text-align: right;">100.00</td>
<td style="text-align: right;">1.91</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">0.04396</td>
</tr>
</tbody>
</table>
<p>In this cluster, there is an over-representation of those who adhere to most of the proposals to increase their participation in the R community. Most of them have never participated in a user group meeting. The cluster gathers a large number of people who use blogs to get help, but also a large proportion of people who do not use Twitter. They prefer to use a medium like Facebook or mailing lists for news.</p>
<p>From a demographic point of view, the cluster contains a significantly higher proportion of women than the respondent population, and a larger proportion of those with a master’s or undergraduate degree. People under the age of 30 are also over-represented.</p>
<p>Note that we need to be cautious concerning the interpretation of the clustering as it varies depending on the number of MCA components selected. The stability of the solution should be investigated further. In addition, the number of individuals per cluster may slightly vary as there is a “consolidation step”<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> which is applied, i.e.&nbsp;a k-means algorithm applied after the hierarchical clustering.</p>
</section>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Missing values occurring in the questions relative to the involvement in the R community often occur on all the questions simultaneously.</p>
<p>Two main groups of respondents have been highlighted:</p>
<ul>
<li><p>People who do not feel they are part of the R community, but who would like to participate in workshops, or an R user group meeting close to them (from a geographic, or demographic point of view). They are more likely women, people with master or undergraduate degree.</p></li>
<li><p>People who feel they are part of the R community, but do not have time to participate to meetings. They are more likely men, people with caring responsibilities, or people with a doctorate.</p></li>
</ul>
<p>In addition, since we recoded many variables, we could make recommendations for the next questionnaire. In particular, we suggest using “yes” and “no” answers for the checkboxes to distinguish missing values from “no”.</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>For more details about the classification based on principal components methods, see: Francois Husson, Jerome Pages, Sebastien Le. Exploratory Multivariate Analysis by Example Using R. CRC Press Taylor &amp; Francis, pp.240, 2010, Chapman &amp; Hall/CRC Computer Science &amp; Data Analysis.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>For more details about the classification based on principal components methods, see: Francois Husson, Jerome Pages, Sebastien Le. Exploratory Multivariate Analysis by Example Using R. CRC Press Taylor &amp; Francis, pp.240, 2010, Chapman &amp; Hall/CRC Computer Science &amp; Data Analysis.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© 2023 Forwards, under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a> license.<br></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>