---
title: "Education"
listing:
  id: edu-listing
  contents: "../blog/**"
  include:
    categories: "education" 
  type: default
  categories: false
  sort-ui: true
  filter-ui: true
title-block-banner: false
---

The Forwards teaching team support the work of the taskforce via the following projects:

* **R Coding Workshops**: in-person workshops taught or supported by members of Forwards, targeting members of under-represented groups. So far, the team has focused on two types of workshop: package development workshops for women and coding workshops for high school girls. See the [workshops page](workshops), for further details, up-coming and past workshops.

* **Forwards Teaching materials**: materials from the workshops with licenses that allow them to be re-used and re-mixed for use in R-Ladies groups, R user groups and beyond. See the [workshops GitHub](https://github.com/forwards/workshops) for materials from the package development workshop and the [teaching examples GibHub](https://github.com/forwards/teaching_examples) for material from the high school girls workshop.

* **Teaching Examples**: a collection of diverse and inclusive examples for use in the teaching of R and data science. For more information and to get involved, see the [teaching examples GitHub](https://github.com/forwards/teaching_examples).

## Education blog posts

::: {#edu-listing}
:::
